name: Build e Push - Múltiplas Imagens

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Builda a Imagem do PROXY ---
      - name: Build e push do PROXY (step-daddy-live-hd)
        uses: docker/build-push-action@v5
        with:
          context: .  # Contexto é a raiz
          file: ./Dockerfile
          push: true
          # A Action vai pegar os Secrets do GitHub e injetar como 'args' no build
          build-args: |
            PORT=${{ secrets.PORT }}
            API_URL=${{ secrets.API_URL }}
            PROXY_CONTENT=${{ secrets.PROXY_CONTENT }}
            SOCKS5=${{ secrets.SOCKS5 }}
          # Mude o nome da imagem como preferir
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/daddyliveproxy-proxy:latest

      # --- Builda a Imagem do GERADOR ---
      - name: Build e push do GERADOR (gerador-live)
        uses: docker/build-push-action@v5
        with:
          context: ./schedule # Contexto é a pasta 'schedule'
          file: ./schedule/Dockerfile
          push: true
          # Este não precisa de 'build-args'
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/daddyliveproxy-scheduler:latest