name: Build e Push - GitHub Container Registry (GHCR)

on:
  push:
    branches: [ "main" ]

# Define permissões para que o job possa escrever no GHCR
permissions:
  contents: read
  packages: write # <--- Esta linha é essencial

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # 1. Faz login no GitHub Container Registry (ghcr.io)
      # Ele usa um token automático do GitHub, não precisa de Secrets!
      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Seu nome de usuário (raphaelfuchter)
          password: ${{ secrets.GITHUB_TOKEN }}  # Este é um token especial gerado pelo GitHub

      # --- Builda a Imagem do PROXY ---
      - name: Build e push do PROXY (step-daddy-live-hd)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            PORT=${{ secrets.PORT }}
            API_URL=${{ secrets.API_URL }}
            PROXY_CONTENT=${{ secrets.PROXY_CONTENT }}
            SOCKS5=${{ secrets.SOCKS5 }}
          # 2. O nome da imagem agora usa o prefixo ghcr.io
          tags: ghcr.io/${{ github.repository_owner }}/daddyliveproxy-proxy:latest

      # --- Builda a Imagem do GERADOR ---
      - name: Build e push do GERADOR (gerador-live)
        uses: docker/build-push-action@v5
        with:
          context: ./schedule
          file: ./schedule/Dockerfile
          push: true
          # 3. O nome da imagem aqui também usa ghcr.io
          tags: ghcr.io/${{ github.repository_owner }}/daddyliveproxy-scheduler:latest